server:
  port: 8080

spring:
  application:
    name: webappOnSpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/dataBase
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
