server:
  port: 8080

spring:
  application:
    name: webappOnSpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/dataBase
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
